# Generated by Django 6.1.1 on 2026-09-16 08:45

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive template name.", max_length=255
                    ),
                ),
                (
                    "grist_row_id",
                    models.CharField(
                        help_text="Source row ID in Grist for webhook upsert.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "email_signature",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Standardized email signature template.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=1024)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("doc", "Word / Text Document"),
                            ("link", "Web Link"),
                        ],
                        default="pdf",
                        max_length=32,
                    ),
                ),
                (
                    "grist_row_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="onboarding.template",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Colleague",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full name and role.", max_length=255),
                ),
                (
                    "tchap_link",
                    models.URLField(
                        help_text="Direct link to start discussion on Tchap.",
                        max_length=1024,
                    ),
                ),
                (
                    "grist_row_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colleagues",
                        to="onboarding.template",
                    ),
                ),
            ],
            options={
                "db_table": "colleagues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Institutional email address, primary identity.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full display name.", max_length=255),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Manager"), ("new_agent", "New Agent")],
                        default="new_agent",
                        max_length=32,
                    ),
                ),
                (
                    "signature_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the agent has validated their email signature.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned onboarding template.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="onboarding.template",
                    ),
                ),
            ],
            options={
                "db_table": "agents",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Task action label.", max_length=512),
                ),
                (
                    "service_link",
                    models.URLField(
                        blank=True,
                        help_text="Deep link to a relevant Suite service.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order enforcing sequential unlocking.",
                    ),
                ),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("API_CHECK", "API Check (e.g. Fichiers)"),
                            ("MANUAL", "Manual (Honor System)"),
                            ("GRIST", "Grist Task"),
                            ("SIGNATURE", "Signature Validation"),
                        ],
                        default="MANUAL",
                        max_length=32,
                    ),
                ),
                (
                    "grist_row_id",
                    models.CharField(
                        blank=True,
                        help_text="Grist row ID for deterministic in-place sync.",
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_items",
                        to="onboarding.template",
                    ),
                ),
            ],
            options={
                "db_table": "todo_items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AgentTodoStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_statuses",
                        to="onboarding.agent",
                    ),
                ),
                (
                    "todo_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_statuses",
                        to="onboarding.todoitem",
                    ),
                ),
            ],
            options={
                "db_table": "agent_todo_statuses",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.URLField(max_length=1024)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "grist_row_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="onboarding.template",
                    ),
                ),
            ],
            options={
                "db_table": "trainings",
                "ordering": ["title"],
            },
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="idx_agents_email_lower",
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(
                fields=["template", "order"], name="idx_todo_items_template_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="agenttodostatus",
            constraint=models.UniqueConstraint(
                fields=("agent", "todo_item"), name="unique_agent_todo_status"
            ),
        ),
    ]
