# Generated by Django 6.1.1 on 2026-09-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed instructions or explanation.",
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="doc_url",
            field=models.URLField(
                blank=True,
                help_text="Documentation guide link.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
