# Generated by Django 6.1.1 on 2026-09-17 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_todoitem_description_todoitem_doc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Optional agent assignment for manager-created custom tasks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_todo_items', to='onboarding.agent'),
        ),
    ]
