# Generated by Django 6.1.1 on 2026-09-17 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_todoitem_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='arrival_date',
            field=models.DateField(blank=True, help_text='Arrival / start date in the administration.', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='colleagues_to_meet',
            field=models.ManyToManyField(blank=True, help_text='Key colleagues / mentors this agent should meet during onboarding.', related_name='meeting_agents', to='onboarding.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Departure / end date if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='job_title',
            field=models.CharField(blank=True, default='', help_text='Professional title/role (e.g. Chargé de mission numérique).', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Direct phone number.', max_length=64),
        ),
        migrations.CreateModel(
            name='AgentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, help_text='Date the comment was recorded.', null=True)),
                ('text', models.TextField(help_text='Note or observation text.')),
                ('grist_row_id', models.CharField(help_text='Source row ID in Grist Comments table.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text='Target agent for this note.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='onboarding.agent')),
            ],
            options={
                'db_table': 'agent_comments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official service name.', max_length=255)),
                ('initials', models.CharField(blank=True, default='', help_text='Short initials (e.g. DN).', max_length=32)),
                ('color', models.CharField(blank=True, default='#000091', help_text='Hex color code.', max_length=32)),
                ('logo_url', models.CharField(blank=True, default='', help_text='URL of service logo.', max_length=1024)),
                ('manager_name', models.CharField(blank=True, default='', help_text='Service director/manager display name.', max_length=255)),
                ('manager_email', models.EmailField(blank=True, default='', help_text='Service manager contact email.', max_length=255)),
                ('grist_row_id', models.CharField(help_text='Source row ID in Grist Services table.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_template', models.ForeignKey(blank=True, help_text='Default onboarding template for this service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_services', to='onboarding.template')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Department / service this agent belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='onboarding.service'),
        ),
    ]
