"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

from corsheaders.defaults import default_headers
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# "development" or "production" — use this instead of DEBUG to branch
# behavior that isn't just about showing tracebacks (e.g. forcing
# HTTPS, enabling Sentry, cookie security flags).
DJANGO_ENVIRONMENT = env("DJANGO_ENVIRONMENT", default="development")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-*)_o6thi#%2jx&h!_-aqhtm7@)bryd^%xw@uffc==eq%)qf^3^",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "backend", "testserver", "0.0.0.0", "*"],
)
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "src.onboarding",
    "mozilla_django_oidc",
]

AUTHENTICATION_BACKENDS = [
    "mozilla_django_oidc.auth.OIDCAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:3000"]
)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-dev-user-email",
    "x-grist-webhook-token",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "src.onboarding.authentication.DevOrKeycloakAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}

ROOT_URLCONF = "src.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "src.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": env.db(
        "DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# OIDC (Keycloak, dedicated to this project — see docker/keycloak/realm.json)
# https://mozilla-django-oidc.readthedocs.io/en/stable/settings.html

OIDC_RP_CLIENT_ID = env("OIDC_RP_CLIENT_ID", default="bienvenue-lasuite")
OIDC_RP_CLIENT_SECRET = env(
    "OIDC_RP_CLIENT_SECRET", default="ThisIsAnExampleKeyForDevPurposeOnly"
)
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile"

OIDC_OP_AUTHORIZATION_ENDPOINT = env(
    "OIDC_OP_AUTHORIZATION_ENDPOINT",
    default="http://localhost:8180/realms/bienvenue-lasuite/protocol/openid-connect/auth",
)
OIDC_OP_TOKEN_ENDPOINT = env(
    "OIDC_OP_TOKEN_ENDPOINT",
    default="http://localhost:8180/realms/bienvenue-lasuite/protocol/openid-connect/token",
)
OIDC_OP_USER_ENDPOINT = env(
    "OIDC_OP_USER_ENDPOINT",
    default="http://localhost:8180/realms/bienvenue-lasuite/protocol/openid-connect/userinfo",
)
OIDC_OP_JWKS_ENDPOINT = env(
    "OIDC_OP_JWKS_ENDPOINT",
    default="http://localhost:8180/realms/bienvenue-lasuite/protocol/openid-connect/certs",
)
OIDC_OP_LOGOUT_ENDPOINT = env(
    "OIDC_OP_LOGOUT_ENDPOINT",
    default="http://localhost:8180/realms/bienvenue-lasuite/protocol/openid-connect/logout",
)
OIDC_OP_LOGOUT_URL_METHOD = "src.oidc.provider_logout"
OIDC_STORE_ID_TOKEN = True

LOGIN_URL = "oidc_authentication_init"
LOGIN_REDIRECT_URL = env("LOGIN_REDIRECT_URL", default="http://localhost:3000/")
LOGIN_REDIRECT_URL_FAILURE = env(
    "LOGIN_REDIRECT_URL_FAILURE", default="http://localhost:3000/"
)
LOGOUT_REDIRECT_URL = env("LOGOUT_REDIRECT_URL", default="http://localhost:3000/")
ALLOW_LOGOUT_GET_METHOD = True

# Silence expected 4xx HTTP logs from test suite to keep output clean
if "test" in sys.argv:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "null": {
                "class": "logging.NullHandler",
            },
        },
        "loggers": {
            "django.request": {
                "handlers": ["null"],
                "level": "CRITICAL",
                "propagate": False,
            },
        },
    }

